### PR TITLE
Per cell hamming

### PR DESCRIPTION
**Pull request by Leonievb**

### CODE REVIEW

**Comment by acorbat** [comment]
Hi Leonie,

I'm a bit lost in time with this branch. I thought most (if not all) the changes were already implemented in the most updated version. Was there something missing?

**Comment by Leonievb** [comment]
Hey Agus,
No, I actually just wanted to merge the changes into the main branch so that per-cell hamming distance correction is a general feature. I just ran trex and encountered problems, because molecules were corrected globally.
Do you remember if you implemented this code for run10x only or also for smartseq2/3?

**Comment by acorbat** [comment]
I'm sorry, I never had the time to go through smartseq2/3 to add the functionality. O do keep this #64 in the back of my mind, but I'm afraid that as I never went through smartseq I am not sure where the differences would be.

I only skimmed the changes, but to me it looks like per cell correction is working for 10X (see [here](https://github.com/frisen-lab/TREX/blob/f528165a59409b8adc9c6e99066a91c70ed7434f/src/trex/cli/run10x.py#L141)). Although the modification was done before implementing the [changelog](https://github.com/frisen-lab/TREX/blob/main/CHANGES.md).

On the other hand, I see options to filter out too short cloneIDs. We discussed this a couple times for at least two reasons:
1. There is a downstream step to filter them out, but it might be good to remove them since the beginning.
2. Using Shannon information to remove "odd" sequences will probably remove the short ones as short sequences also have small Shannon information values.

I really don't remember what happened with this branch...

**Comment by Leonievb** [comment]
Hmm weird, the --per-cell flag exists in the smartseq3 help section and I am using it. But the truth is that it doesn't seem to make a difference in the outcome. However, changing from the main to the per_cell_hamming branch led to a strong difference in the outcome when using exactly the same command line without --per-cell flag. Here is the clone histogram from running `trex smartseq3` on the main branch and on the per_cell_hamming branch:
1. main
1   586
    2    27
    3    12
    4     8
    5     6
    6     2
    7     5
    9     1
   10     1
   12     2
   14     1
   17     1
   18     1
   19     1
   24     1
   39     1
   50     1
   59     1
   85     1
2. per_cell_hamming
Clone size histogram
 size count
    1    15
 1341     1
 
 The former is much more likely correct. So I might remove this pull request as there seem to be some issues with this branch

**Comment by Leonievb** [comment]
So you mean these two options you mentioned are implemented in the branch or are not?

**Comment by acorbat** [comment]
I agree!

I think this was an old branch we were working on and then we decided to separate the modifications into different branches.

With regards to --per-cell in smartseq, I think the argument was added as a general argument, but it was not implemented  in smartseq so it won't change the output. I believe implementing it will mostly be call a couple functions already implemented and then designing (or updating) some tests.

**Comment by Leonievb** [comment]
ok good to know, thanks Agus. I am going to close this pull request then, cause it should not override the main branch.

**Pull request closed without merging**
